// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozmoqurowlexforzmily.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96bW9xdXJvd2xleGZvcnptaWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Njg1ODAsImV4cCI6MjA2NTE0NDU4MH0.di8A83QfL7EN3EPV4Pau14J8VZBisNLxmhiKQiGCueA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);